channels:
- conda-forge
- nodefaults
dependencies:
- numpy =1.26.4
- setuptools >=68
- pandas
- python >=3.11,<3.14
- pyiron_base
- pybis =1.37.0
- python-xxhash =3.5.0
- boto3 =1.35
- ase =3.25.0
- numpy==1.26.4
- pyiron
- pyiron_atomistics=0.7.18
- lammps
- nglview
- pyiron-data >=0.0.30
- iprpy-data
