channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pyiron
  - pyiron_base=0.13.0
  - pyiron_atomistics=0.7.8
  - lammps
  - nglview
  - pyiron-data >=0.0.30
  - pybis=1.37.0
  - python-xxhash=3.5.0
  - iprpy-data
  - boto3=1.35
