channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- numpy
- lammps =2024.02.07=*_openmpi_*
- setuptools >=68
- pandas
- python >=3.11,<3.14
- pyiron_atomistics =0.7.18
- pyiron_base
- pyiron-data >=0.0.30
- pybis=1.37.0
- python-xxhash=3.5.0
- boto3=1.35
