channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- numpy =1.26.4
- setuptools >=68
- pandas =2.3.2
- python >=3.11,<3.14
- pyiron_base =0.15.3
- pybis =1.37.4
- python-xxhash =3.6.0
- boto3 =1.35
- structuretoolkit =0.0.34
- spglib =2.6.0
- ase =3.25.0
