channels:
- conda-forge
dependencies:
- ipykernel
- myst-parser
- nbsphinx
- sphinx-gallery
- sphinx-rtd-theme
- versioneer
- numpy =2.3.1
- setuptools >=68
- pandas
- python >=3.11,<3.14
- pyiron_base
- pybis =1.37.0
- python-xxhash =3.5.0
- boto3 =1.35
- structuretoolkit =0.0.34
